# ***************************Aton测试配置**************************** #
# 当前激活的配置名称(请不要修改)
profile: press
# 密码加密配置
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
#Spring框架内部配置
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://192.168.9.191:3306/alaya_browser_hrpatp201018v10000hyp?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: ENC(bpshgjWOgn2d+oGmSTBPNA==)
    password: ENC(bpshgjWOgn2d+oGmSTBPNA==)
  #Redis配置
  redis:
    cluster:
      max-redirects: 3
      nodes: 192.168.9.145:6379,192.168.9.145:6380,192.168.9.146:6379,192.168.9.146:6380,192.168.9.147:6379,192.168.9.147:6380
    password: fdfjksdfhkf
  #ES配置
  elasticsearch:
    high-level-client:
      hosts: 192.168.9.145,192.168.9.146,192.168.9.147
      port: 9200
      schema: http
      #username: elastic
      #password: changeme
    index:
      blockIndexName: ${platon.es-namespace}_block
      transactionIndexName: ${platon.es-namespace}_transaction
      delegationIndexName: ${platon.es-namespace}_delegation
      nodeOptIndexName: ${platon.es-namespace}_nodeopt
      delegationRewardIndexName: ${platon.es-namespace}_delegation_reward
      transferTxIndexName: ${platon.es-namespace}_transfer_tx
      erc20TxIndexName: ${platon.es-namespace}_erc20_tx
      erc721TxIndexName: ${platon.es-namespace}_erc721_tx
#日志配置
logging:
  file:
    name: ./logs/${spring.application.name}-${version}-${profile}.log
  #日志级别
  level:
    org.springframework: info
    org.springframework.retry: info
#同步时的索引查询分页参数配置
paging:
  block:
    pageSize: 2000
    pageCount: 250
  transaction:
    pageSize: 2000
    pageCount: 250
disruptor:
  queue:
    block:
      buffer-size: 1024
      batch-size: 256
    transaction:
      buffer-size: 1024
      batch-size: 1024
    nodeopt:
      buffer-size: 1024
      batch-size: 512
    node:
      buffer-size: 1024
      batch-size: 2
    stake:
      buffer-size: 1024
      batch-size: 3
    delegation:
      buffer-size: 1024
      batch-size: 256
    proposal:
      buffer-size: 1024
      batch-size: 3
    vote:
      buffer-size: 1024
      batch-size: 3
    rpplan:
      buffer-size: 1024
      batch-size: 3
    estimate:
      buffer-size: 1024
      batch-size: 1024
    reward:
      buffer-size: 1024
      batch-size: 1024
    slash:
      buffer-size: 1024
      batch-size: 3
    address:
      buffer-size: 1024
      batch-size: 1024
    token:
      buffer-size: 1024
      batch-size: 50
    token-holder:
      buffer-size: 1024
      batch-size: 50
    token-inventory:
      buffer-size: 1024
      batch-size: 50
    token-address:
      buffer-size: 1024
      batch-size: 5000
    token-transfer:
      buffer-size: 1024
      batch-size: 20
#PlatOn相关配置
platon:
  #Redis命名空间
  redis-namespace: browser:${profile}
  #Es索引命名空间
  es-namespace: browser_${profile}
  # 地址HRP前缀
  addressPrefix: lat
  # 金额显示单位
  valueUnit: LAT
  # 交易输入参数并行解码线程数
  txLogDecodeThreadNum: 200
  # Web3j访问地址
  web3j:
    #HTTP或WS
    protocol: http
    addresses: 192.168.9.144:6789,192.168.9.144:6790
  # 质押节点统计年化率最多取多少个连续周期
  maxSettlePeriodCount4AnnualizedRateStat: 4
  #PlatON初始总发行量(ATP)
  initIssueAmount: 10000000000
  #每年固定增发比例
  addIssueRate: 0.025
  #每年增发分配给激励池的比例
  incentiveRateFromIssue: 0.8
  #每个共识轮中回退多少个块是选举下一轮验证人的时机
  electionBackwardBlockCount: 20
  #10年内基金会向激励池填充额度: <第几年-补贴金额(ATP)>
  foundationSubsidies: {
    '1':62215742.00000000,
    '2':55965742.00000000,
    '3':49559492.00000000,
    '4':42993086.00000000,
    '5':36262520.00000000,
    '6':29363689.00000000,
    '7':22292388.00000000,
    '8':15044304.00000000,
    '9':7615018.00000000
  }
  # 初始内置节点默认质押金额(ATP)
  defaultStakingLockedAmount: 1500000
  #区块最大Gas限制
  maxBlockGasLimit: 201600000
  #提案url参数模板
  proposalUrlTemplate: https://github.com/danielgogo/PIPs/blob/master/PIP-%s.md
  #提案pip_num参数模板
  proposalPipNumTemplate: PIP-%s
  #keysBase网址
  keyBase: https://keybase.io/
  #keyBase api
  keyBaseApi: _/api/1.0/user/lookup.json?key_suffix=
  #链id
  chainId: 100
  # 地址重复使用的最大次数
  addressReusedTimes: 50
  #节点条数
  nodeMaxCount: 1000
  #质押条数
  stakeMaxCount: 3000
  #委托条数
  delegateMaxCount: 6000000
  #提案条数
  proposalMaxCount: 600
  #投票最大条数
  voteMaxCount: 6000
  #rpplan最大条数
  rpplanMaxCount: 6000
  #slash最大条数
  slashMaxCount: 600
  #地址最大条数
  addressMaxCount: 1500000
  #区块最大条数
  blockMaxCount: 15552000
  #日志最大条数
  nodeoptMaxCount: 1788000
  #代币合约最大条数
  tokenMaxCount: 100000
  #代币合约最大条数
  tokenERC20MaxCount: 50000
  #代币合约最大条数
  tokenERC721MaxCount: 50000
  #每个代币与地址建立关系的数量
  #addressCountPerToken: 1000000000
  addressCountPerToken: 100000
  #每个区块的交易数
  txCountPerBlock: 200
  #每个委托奖励数
  rewardMaxCount: 2000000
  #gas 数据
  estimateMaxCount: 1000000
  #交易数
  tokenTransferMaxCount: 3110400000
