# ***************************开发配置**************************** #
# 当前激活的配置名称(请不要修改)
profile: test
# 密码加密配置
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
#Spring框架内部配置
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://52.74.18.166:3306/scan_platon?useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: anoledb
#PlatOn相关配置
platon:
  #链id
  chainId: 20220317
  # Web3j访问地址
  web3j:
    #HTTP或WS
    protocol: HTTP
    addresses: 52.74.18.166:6790
  #区块最大Gas限制
  maxBlockGasLimit: 201600000
  # 初始内置节点默认质押金额(ATP)
  defaultStakingLockedAmount: 150000
  # 交易输入参数并行解码线程数
  txLogDecodeThreadNum: 200
task:
  #允许更新的最大地址数量
  maxAddressCount: 5004
  #每次批量查询锁仓余额的最大数量
  maxBatchSize: 100
  #基金会地址统计cron表达式：
  #    生产：每10分钟执行一次：0 0/10 * * * ?
  #    测试：每10秒钟执行一次：0/10 * * * * ?
  fundAddressCron: 0 0/6 * * * ?
  #内置合约地址统计cron表达式：
  #    生产：每1分钟执行一次：0 0/1 * * * ?
  #    测试：每5秒钟执行一次：0/5 * * * * ?
  innerContractCron: 0/10 * * * * ?
  #地址统计任务批次大小
  addressBatchSize: 1000
#日志配置
logging:
  #日志级别
  level:
    org.springframework: error
    com.platon.browser.task: debug
  file:
    name: ./logs/${spring.application.name}-${profile}.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} | %-5level | %thread | trace-id[%X{trace-id}] | %logger{50}[%L] | %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} | %-5level | %thread | trace-id[%X{trace-id}] | %logger{50}[%L] | %msg%n"
  logback:
    rollingpolicy:
      # 日志文件大小上限，达到该上限后，会自动压缩
      max-file-size: 200MB
      # 日志归档的文件名，日志文件达到一定大小之后，自动进行压缩归档
      file-name-pattern: ./logs/${spring.application.name}-${profile}-%d{yyyy-MM-dd}-%i.log.gz
      # 日志文件保存的天数
      max-history: 90
      # 是否在应用启动时进行归档管理
      clean-history-on-start: true
