# ***************************_DESCRIPTION_**************************** #
# 应用版本
version: _VERSION_
#Spring应用配置
spring:
  application.name: browser-sync
  #Redis集群配置
  redis:
    database: 0
    key:
      #区块列表
      blocks: browser:${version}:${profile}:blocks
      #交易列表
      transactions: browser:${version}:${profile}:transactions
      #统计信息
      networkStat: browser:${version}:${profile}:networkStat
    max-item: 500000