# ***************************Aton开发配置**************************** #
# 当前激活的配置名称(请不要修改)
profile: dev
#Spring框架内部配置
spring:
  #Redis配置
  redis:
    cluster:
      max-redirects: 3
      nodes: 192.168.9.191:7001,192.168.9.191:7002,192.168.9.191:7003,192.168.9.191:7004,192.168.9.191:7005,192.168.9.191:7006
    password: platscan
  #ES配置
  elasticsearch:
    high-level-client:
      hosts: 192.168.120.103,192.168.120.104,192.168.120.105
      port: 9200
      schema: http
      blockIndexName: browser_block_aton_${profile}
      transactionIndexName: browser_transaction_aton_${profile}
      delegationIndexName: browser_delegation_aton_${profile}
      nodeOptIndexName: browser_nodeopt_aton_${profile}
#日志配置
logging:
  file: ./logs/${spring.application.name}-${version}-${profile}.log
  #日志级别
  level:
    org.springframework: error
    org.springframework.retry: error
#同步时的索引查询分页参数配置
paging:
  block:
    pageSize: 2000
    pageCount: 250
  transaction:
    pageSize: 2000
    pageCount: 250

#PlatOn相关配置
platon:
  # 交易输入参数并行解码线程数
  txLogDecodeThreadNum: 10
  # Web3j访问地址
  web3j:
    #HTTP或WS
    protocol: WS
    addresses: 192.168.112.172:8788
  # 质押节点统计年化率最多取多少个连续周期
  maxSettlePeriodCount4AnnualizedRateStat: 4
  #PlatON初始总发行量(ATP)
  initIssueAmount: 10000000000
  #每年固定增发比例
  addIssueRate: 0.025
  #每年增发分配给激励池的比例
  incentiveRateFromIssue: 0.8
  #每个共识轮中回退多少个块是选举下一轮验证人的时机
  electionBackwardBlockCount: 20
  #10年内基金会向激励池填充额度: <第几年-补贴金额(ATP)>
  foundationSubsidies: {
    '1':62215742,
    '2':55965742,
    '3':49559492,
    '4':42993086,
    '5':36262520,
    '6':29363689,
    '7':22292388,
    '8':15044304,
    '9':7615018
  }
  # 初始内置节点默认质押金额(ATP)
  defaultStakingLockedAmount: 1500000
  #区块最大Gas限制
  maxBlockGasLimit: 100800000
  #提案url参数模板
  proposalUrlTemplate: https://github.com/danielgogo/PIPs/blob/master/PIP-%s.md
  #提案pip_num参数模板
  proposalPipNumTemplate: PIP-%s
  #keysBase网址
  keyBase: https://keybase.io/
  #keyBase api
  keyBaseApi: _/api/1.0/user/autocomplete.json?q=