# ***************************_DESCRIPTION_**************************** #
# 应用版本
version: _VERSION_
#Spring应用配置
spring:
  application.name: browser-press
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  #Redis集群配置
  redis:
    database: 0
    key:
      #区块列表
      blocks: ${platon.redis-namespace}:blocks
      #交易列表
      transactions: ${platon.redis-namespace}:transactions
      #统计信息
      networkStat: ${platon.redis-namespace}:networkStat
      #内部转账交易
      transferTx: ${platon.redis-namespace}:transferTx
      #erc20交易
      erc20Tx: ${platon.redis-namespace}:erc20Tx
      #erc721交易
      erc721Tx: ${platon.redis-namespace}:erc721Tx
      maxItem: 500000
# MyBatis配置（注意：一定要对应mapper映射xml文件的所在路径）
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  # 实体类别名配置（注意：对应实体类的路径）
  type-aliases-package: com.platon.browser.dao.entity